const data= {
    products: [
        {
            _id :'1',
            name:'Bitcoin',
            category: 'Crypto',
            image: '/images/p-4.jpg',
            price:28.17,
            brand:'Satoshi',
            rating:4.7,
            numReviews:100,
            description:'Genesis quiality',
        },
        {
            _id :'2',
            name:'Ethereum',
            category: 'Crypto',
            image: '/images/p-3.jpg',
            price:8.7,
            brand:'Vitalik',
            rating:4.5,
            numReviews:70,
            description:'Etherium Ecosystem',
        },
        {
            _id :'3',
            name:'Cardano',
            category: 'Pants',
            image: '/images/p-3.jpg',
            price:28.17,
            brand:'Satoshi',
            rating:4.7,
            numReviews:10,
            description:'Top quality',
        },
        {
            _id :'4',
            name:'Polygon',
            category: 'Shirts',
            image: '/images/p-4.jpg',
            price:28.17,
            brand:'Satoshi',
            rating:4.7,
            numReviews:10,
            description:'Genesis quality',
        },
        {
            _id :'5',
            name:'Adidas pants',
            category: 'Pants',
            image: '/images/p-3.jpg',
            price:28.17,
            brand:'Adidas',
            rating:4.7,
            numReviews:15,
            description:'Genesis quiality',
        },
        {
            _id :'6',
            name:'Puma shoes',
            category: 'Shoes',
            image: '/images/p-4.jpg',
            price:28.17,
            brand:'Puma',
            rating:3.7,
            numReviews:10,
            description:'Genesis quiality',
        },
    ],
};
export default data;